version: "3.8"
services:
    php-apache:
        container_name: php-apache
        build:
            context: ./php
            target: php
            args:
                - APP_ENV=${APP_ENV}
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8080:80
        depends_on:
            - database
    database:
        container_name: database
        image: mysql:8.0
        ports:
            -   3306:3306
        environment:
            - MYSQL_DATABASE = default
            - MYSQL_USER = root
            - MYSQL_PASSWORD =
            - MYSQL_ROOT_PASSWORD =
        volumes:
            - db-data:/var/lib/mysql

volumes:
    db-data: ~
